name: gerardggf_cv
description: "CV Gerard Gutiérrez Flotats"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  package_info_plus: ^8.3.1
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pdfs/
    - assets/img/
    - assets/img/projects/
