name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"
      - run: flutter pub get
      - run: flutter pub run slang
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build web --release --base-href "/"
      - run: mkdir -p build/web/pdfs && cp -r assets/pdfs/* build/web/pdfs/ || true
      - run: cp build/web/index.html build/web/404.html
      - run: touch build/web/.nojekyll
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
